version: '3.2'
services:
  jenkins:
    build:
      context: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home/
    ports:
      - "8080:8080"
      - "5000:5000"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
  gogs:
    image: gogs/gogs:0.11.4
    volumes:
      - gogs_data:/data/
    ports:
      - "2222:22"
      - "3000:3000"

volumes:
  jenkins_data:
    driver: local
  gogs_data:
    driver: local
